### ISSUE TITLE
Unknown error, DLL dailed

### ISSUE THREAD

**Issue by suchifa** [bluaxees/Poricom#16]
![Poricom_2022-12-01_18-17-42](https://user-images.githubusercontent.com/119622506/205130394-a1a8c8cb-7748-4bc4-a40b-c60076d12623.png)

Hello. I know nothing about Python. Installed it in order to run the shortcut.exe in Windows10, but I get this error. Thank you.

**Comment by bluaxees** [comment]
What GPU do you have? Also can you check if you have CUDA enabled?

**Comment by suchifa** [comment]
> What GPU do you have? Also can you check if you have CUDA enabled? (Include the version number if so)

RADEON RX 580. No CUDA, because it's not Nvidia.
Thank you.

**Comment by bluaxees** [comment]
Download the zip file `Poricom-CMD-v0.3.1.7z` from [this link](https://github.com/bluaxees/Poricom/releases/tag/v0.3.1). This would open both the command line and the app. It should now work since it includes all the binaries. If it does, can you please post a picture of the command line? It should look like this: 
![image](https://user-images.githubusercontent.com/45705751/205474703-5fa4f599-ff4e-4f79-9ba5-01a91030cb74.png)

**Comment by suchifa** [comment]
Reinstalled AMD drivers, same problems. Reinstalled Java: KanjiTomo fixed, but Poricom still does not work. Also tried reinstalling Python... No black console screen with the cmd, and this error with the usual zip.

![Poricom_2022-12-06_19-56-42](https://user-images.githubusercontent.com/119622506/205998052-73f3dc08-b199-470f-a537-6284e430f8ce.png)

Same error. There's an intrinsic problem here. Is it the code? Is it I lack any librarie or DLL whatsoever?

Thanks in advance.

**Comment by suchifa** [comment]
Exactly same error lines... 
![cmd_2022-12-09_18-55-19](https://user-images.githubusercontent.com/119622506/206763608-b849e554-f0b2-4ba8-9c68-6e139ab131dc.png)

**Comment by bluaxees** [comment]
I think the issue is you have a non-NVIDIA GPU. I uploaded a another zip file (`Poricom-CPU-v0.3.1.7z`) in the latest release. Please tell me if it works

**Comment by suchifa** [comment]
![Poricom_2022-12-11_22-36-46](https://user-images.githubusercontent.com/119622506/206930190-a3aac746-a522-45b2-8b4a-907ea6a21ba5.png)

Error in a different line, it seems

**Comment by bluaxees** [comment]
That was my last attempt unfortunately. I don't really know how to help you since I'm not sure what's causing this issue
